version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://db:27017/taskmanager
      - JWT_SECRET=your_jwt_secret_key
  db:
    image: mongo:4.2
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
